/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula6;
import Ferramentas.Globais;
import modelos.Questionario;
/**
 *
 * @author Windows 10
 */
public class TelaQuestionario extends javax.swing.JFrame {
    int cont = 0;
    int aux = 0;
    int acertos = 0;
    int erros = 0;
    int total = 0;
    Questionario[] vetorQuestionario = new Questionario[3];

    /**
     * Creates new form TelaQuestionario
     */
    public TelaQuestionario() {
        initComponents();
        
        
        
        Questionario questao1 = new Questionario();
        
        questao1.setPergunta("Quanto é 5+5x5");
        questao1.setRespostaA("50");
        questao1.setRespostaB("30");
        questao1.setRespostaC("25");
        questao1.setRespostaCorreta(questao1.getRespostaB());
        
        vetorQuestionario[0]=questao1;
        
        Questionario questao2 = new Questionario();
        
        questao2.setPergunta("Quem Ganhou a última copa do mundo?");
        questao2.setRespostaA("Alemanha");
        questao2.setRespostaB("Bélgica");
        questao2.setRespostaC("França");
        questao2.setRespostaCorreta(questao2.getRespostaC());
        
        vetorQuestionario[1]=questao2;
        
        Questionario questao3 = new Questionario();
        
        questao3.setPergunta("Qual é o unico elemento da tabela periódica que não possúi família?");
        questao3.setRespostaA("Hidrogenio");
        questao3.setRespostaB("Carbono");
        questao3.setRespostaC("Hélio");
        questao3.setRespostaCorreta(questao3.getRespostaA());
        
        vetorQuestionario[2]=questao3;
        
        lblQuestao.setText(vetorQuestionario[cont].getPergunta());
        rbtResposta1.setText(vetorQuestionario[cont].getRespostaA());
        rbtResposta2.setText(vetorQuestionario[cont].getRespostaB());
        rbtResposta3.setText(vetorQuestionario[cont].getRespostaC());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblQuestao = new javax.swing.JLabel();
        rbtResposta1 = new javax.swing.JRadioButton();
        rbtResposta2 = new javax.swing.JRadioButton();
        rbtResposta3 = new javax.swing.JRadioButton();
        btnAvancar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblMensagemErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUESTIONÁRIO");

        lblQuestao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuestao.setText("QUESTÃO 1");
        lblQuestao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        buttonGroup1.add(rbtResposta1);
        rbtResposta1.setText("Resposta 1");

        buttonGroup1.add(rbtResposta2);
        rbtResposta2.setText("Resposta 2");

        buttonGroup1.add(rbtResposta3);
        rbtResposta3.setText("Resposta 3");

        btnAvancar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAvancar.setText("AVANÇAR");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("VOLTAR");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblMensagemErro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMensagemErro.setForeground(new java.awt.Color(255, 0, 0));
        lblMensagemErro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVoltar)
                                .addGap(18, 18, 18)
                                .addComponent(lblMensagemErro, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAvancar))
                            .addComponent(lblQuestao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtResposta2)
                            .addComponent(rbtResposta1)
                            .addComponent(rbtResposta3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQuestao, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbtResposta1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtResposta2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtResposta3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvancar)
                            .addComponent(btnVoltar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblMensagemErro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        if (rbtResposta1.isSelected() || rbtResposta2.isSelected() || rbtResposta3.isSelected()) {
            cont++;
       if(cont >= vetorQuestionario.length){
           cont = 2;
         }else if(cont < vetorQuestionario.length){
           fazerPergunta();
         }
        if (total < 3) {
            contarAcertos();
        } 
            
            lblMensagemErro.setText("");
            buttonGroup1.clearSelection();
        } else {
            lblMensagemErro.setText("ESCOLHA UMA ALTERNATIVA!");
        }
        
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        cont--;
        aux--;
       if(cont <= -1){
           cont = 0;
       }else if(cont > -1){
               fazerPergunta();
       }
    }//GEN-LAST:event_btnVoltarActionPerformed
    
    private void contarAcertos(){
        System.out.println(vetorQuestionario[aux].getRespostaCorreta());
        if (rbtResposta1.isSelected()) {
            if (vetorQuestionario[aux].getRespostaCorreta().equalsIgnoreCase(rbtResposta1.getText())) {
                acertos++;
                Globais.exibirMensagem("ACERTOU");
            }else {
                erros++;
                Globais.exibirMensagem("ERROU");
            }
        }else if (rbtResposta2.isSelected()) {
            if (vetorQuestionario[aux].getRespostaCorreta().equalsIgnoreCase(rbtResposta2.getText())) {
                acertos++;
                Globais.exibirMensagem("ACERTOU");
            }else {
                erros++;
                Globais.exibirMensagem("ERROU");
            }
        }else if (rbtResposta3.isSelected()) {
            if (vetorQuestionario[aux].getRespostaCorreta().equalsIgnoreCase(rbtResposta3.getText())) {
                acertos++;
                Globais.exibirMensagem("ACERTOU");
            }else {
                erros++;
                Globais.exibirMensagem("ERROU");
            }
        }
            total = acertos+erros;
            aux++;
    }
    
    private void fazerPergunta(){
            
            lblQuestao.setText(vetorQuestionario[cont].getPergunta());
            rbtResposta1.setText(vetorQuestionario[cont].getRespostaA());
            rbtResposta2.setText(vetorQuestionario[cont].getRespostaB());
            rbtResposta3.setText(vetorQuestionario[cont].getRespostaC());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuestionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuestionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMensagemErro;
    private javax.swing.JLabel lblQuestao;
    private javax.swing.JRadioButton rbtResposta1;
    private javax.swing.JRadioButton rbtResposta2;
    private javax.swing.JRadioButton rbtResposta3;
    // End of variables declaration//GEN-END:variables
}
